project:
  type: book
  output-dir: docs

book:
  title: "AI developments in higher education"
  author:
    - name: "Gerko Vink"
      orcid: "0000-0001-9767-1924"
  date: last-modified
  doi: "10.5281/zenodo.10867539"
  chapters:
    - index.qmd
    - intro.qmd
    - models.qmd
    - impact.qmd
    - legal.qmd
    - policy.qmd
    - skills.qmd
    - students.qmd
    - teachers.qmd
    - assessment.qmd
    - references.qmd
    - links.qmd
  repo-url: https://github.com/gerkovink/ai
  repo-branch: dev
  repo-actions: [edit, issue]

bibliography: references.bib

format:
  html:
    toc-depth: 3
    theme: cosmo
  pdf:
    documentclass: scrreprt



