# Introduction
Make your change
In the last 3 years, the development of generative artificial intelligence (AI) has taken a steep rise. But AI is no new idea. Ever sinds Alan Turing's seminal lecture on the automatic computing machine @turing, computer scientists have worked towards the realization of artificial intelligence. I am not going to give an overview of the history of AI, as others have already created a far better overview than I could ever create - see e.g. [this link](https://toloka.ai/blog/history-of-generative-ai/), [Wikipedia](https://en.wikipedia.org/wiki/Generative_artificial_intelligence) or [this overview](https://bernardmarr.com/a-simple-guide-to-the-history-of-generative-ai/). Bottom line, ever since the development of [GitHub Copilot](https://github.com/features/copilot) in 2021, the field of generative AI has rapidly become accessible to a broader audience. This has a direct impact on education, as the widespread accessibility of generative AI has the potential to impact education, research and policy in higher education. It also has the means to create new opportunities or new divides, therefore I have created this archive to keep track of the developments in generative AI in higher education.

## Aim
The aim of this archive is not to be exhaustive, but rather to provide a structure whereby to categorize past, new and ongoing developments. 

## Contributions
I very much welcome contributions to this page. If you have come across a development, policy or study that is not yet included in this archive, please let me know, or rather, add it yourself. Follow the below outline to see how easy it is to propose changes and additions to this archive. 

I do ask you, however, to not generate your contributed text with AI. I prefer this resources to remain a human-curated archive. 
