# Collection of links {#sec-links}
This is where I collect all the links that I come across. You can see this as a work in progress. Some links will become part of the previous chapters, while other links will remain here. Please regard this as a roughly structured library of relevant resources. 

## Responsibility and conscience
- There is [evidence](https://time.com/6247678/openai-chatgpt-kenya-workers/) that the workers who curate these models are treated unfairly or even inhumanely by their employers. This [interview from March 25](https://blogs.lse.ac.uk/businessreview/2024/03/25/madhumita-murgia-ai-can-do-harm-when-people-dont-have-a-voice/) also outlines how and where AI moderation can harm the people who don't have a voice.

## Assessment given the existence of AI tools
Some links (in no particular order) that cover relevant strategies on how to assess student work, given the existence of AI tools.

- [UCL: Designing assessments in and AI enabled world](https://www.ucl.ac.uk/teaching-learning/generative-ai-hub/designing-assessments-ai-enabled-world)
- [UNF: ChatGPT-proof your course](https://unf.pressbooks.pub/chatgptinhighereducation/chapter/chatgpt-proof-your-course/)
- [UU: Can you still use take-home exams and essays?](https://www.uu.nl/en/education/educational-development-training/knowledge-dossier/the-influence-of-chatgpt-on-assessment-can-you-still-use-take-home-exams-and-essays)
- [Bower, M., Torrington, J., Lai, J.W.M. et al. (2024) How should we change teaching and assessment in response to increasingly powerful generative Artificial Intelligence? Outcomes of the ChatGPT teacher survey. Educ Inf Technol.](https://link.springer.com/article/10.1007/s10639-023-12405-0)
- [TILAPIA tool by Phil Newton & ChatGPT](https://www.dropbox.com/scl/fi/a0knbe4l5vdmpr9l2xsox/AI-resilience-tool-v3.0.png?rlkey=ih87d4jh5lqu9l69ygr44s2se&dl=0)

### Scientific publications
- [Do teachers spot AI?](https://www.sciencedirect.com/science/article/pii/S2666920X24000109?dgcid=raven_sd_aip_email)

## Policy

### Guidelines for students
- [UMCU: Guidelines for GSLS students](https://students.uu.nl/en/gsls/practical-information/generative-ai-guidelines)
- [UMCU: GenAI guidelines for research projects for students and supervisors](https://students.uu.nl/sites/default/files/GSLS%20GenAI%20Research%20Guidelines%20for%20Students%20and%20SupervisorsGSLS%20GenAI%20Research%20Guidelines.pdf)

### Guidelines for teachers
- [UMCU: Guidelines for Incorporating Generative AI (GenAI) in GSLS Education](https://teachersguidegsls.nl/teaching-courses/generative-ai-guidelines/)

### Policy
- [UNESCO: Guidance for generative AI in education and research](https://www.unesco.org/en/articles/guidance-generative-ai-education-and-research)
- [WEF: AI Guidance for responsible use in education](https://www.weforum.org/agenda/2024/01/ai-guidance-school-responsible-use-in-education/)
- [Columbia University](https://provost.columbia.edu/content/office-senior-vice-provost/ai-policy)
- [Duke University](https://learninginnovation.duke.edu/ai-and-teaching-at-duke-2/artificial-intelligence-policies-in-syllabi-guidelines-and-considerations/)
- [@chan2023policy]

## AI skills
- [UMCU: AI skills tutorial for GSLS master students](https://ulearning.uu.nl/enrol/index.php?id=1462)
- [UMCU: AI skills tutorial for GSLS master teachers](https://ulearning.uu.nl/enrol/index.php?id=1598)


## AI for grading student work
- [My presentation on the use and misuse of generative AI in academic education](https://www.gerkovink.com/psy/#/title-slide)
- @kumar2023faculty

